import type { Metadata } from "next";
import React from "react";
import { ClerkProvider } from "@clerk/nextjs";
import ConvexClientProvider from "@/providers/ConvexClientProvider";
import ThemeProviderTravis from "@/providers/ThemeProviderTravis";
import "../styles/global.scss";
import InternationalizationProvider from "@/providers/InternationalizationProvider";
export const metadata: Metadata = {
  title: "travis",
  description: "Generated by lldan",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body>
          <ConvexClientProvider>
            <ThemeProviderTravis>
              <InternationalizationProvider>
                {children}
              </InternationalizationProvider>
            </ThemeProviderTravis>
          </ConvexClientProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
