import type { Metadata } from "next";
import React from "react";
import "../styles/global.scss";
import Providers from "@/providers/Providers";
export const metadata: Metadata = {
  title: "travis",
  description: "Generated by lldan",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
